version: "1.0"  #optional

services:

  frontend:
    # container_name: "anotherName"  # bunu vermezsen baslik container name olur (frontend)
    image: "docker-compose-frontend"
    build: ./frontend
    ports:
      - 3000:3000
      - 80:3000
    restart: on-failure
    depends_on:
      - backend

  backend:
    #varsa kullan. yoksa build et.
    image: "docker-compose-backend"
    #Proje klasörü
    build: ./backend
    ports:
      - 8000:8000    #DisPort:IcPort
    restart: on-failure # hata durumunda start/Stop yap.
    volumes: # fiziksel yollar (external:internal)
      - $PWD/backend/db.sqlite3:/backend/db.sqlite3



