# Generated by Django 4.2.3 on 2023-07-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('cohort', models.CharField(choices=[('FS', 'FullStack'), ('DS', 'DataScience'), ('AWS', 'AWS DevOps')], default='FS', max_length=3)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('register_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('comment', models.TextField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Student List',
                'ordering': ['first_name'],
            },
        ),
    ]
